export const matches = [
  {
    config: {
      css: "",
      currentPage: "fixture_detail",
      navigation: {
        labels: {
          search: "Search",
          searchResults: "Search Results",
        },
        main: [
          {
            label: "Standings",
            link: "&~w=stn~eJyrVipWslJQSk1MSkkzNTTRNTZKNtA1NExN0U0yNbHUNTI1MEq2sDC2TDG0VNJRUMoBKS4p0g0JUqoFAMTyDt4",
            value: "standings",
          },
          {
            label: "Teams",
            link: "&~w=el~eJyrVipWslJQSk1MSkkzNTTRNTZKNtA1NExN0U0yNbHUNTI1MEq2sDC2TDG0VNJRUMoBKS4p0g0JUqoFAMTyDt4",
            value: "entities",
          },
          {
            label: "Statistics",
            link: "&~w=stp~eJyrVipWslJQSk1MSkkzNTTRNTZKNtA1NExN0U0yNbHUNTI1MEq2sDC2TDG0VNJRUMoBKS4p0g0JUqoFAMTyDt4",
            value: "statistics",
          },
        ],
      },
      showEntityLogo: true,
      showPrintButton: false,
      sport: "basketball",
    },
    fixture: {
      attendance: null,
      attendanceLabel: "Seyirci Sayısı",
      competitionName: "Türkiye Sigorta Basketbol Süper Ligi",
      competitors: [
        {
          colors: {
            primary: "051ecd",
            secondary: "031768",
            tertiary: "017bcb",
          },
          draw: false,
          entityId: "a82ec9ef-32c2-11ed-93ce-c5cd151fd515",
          isHome: true,
          link: null,
          logo: "https://images.dc.prod.cloud.atriumsports.com/b179b/25aac0efee6a4f33acaa6b025652626f",
          name: "ANADOLU EFES",
          resultPlace: 1,
          resultStatus: "CONFIRMED",
          score: "102",
          secondaryScore: null,
        },
        {
          colors: {
            primary: "0bcac4",
            secondary: "ece1e1",
            tertiary: "caeff0",
          },
          draw: false,
          entityId: "af7e4c88-32c2-11ed-b619-7bbcc08f45bf",
          isHome: false,
          link: null,
          logo: "https://images.dc.prod.cloud.atriumsports.com/b179b/cc2d7c4aa5b745cebdb8e509cf036400",
          name: "TÜRK TELEKOM",
          resultPlace: 2,
          resultStatus: "CONFIRMED",
          score: "87",
          secondaryScore: null,
        },
      ],
      externalId: "163177",
      fixtureId: "0012e410-32c4-11ed-9f88-255f069c387c",
      fixtureType: null,
      liveDataAvailable: false,
      liveVideoAvailable: false,
      name: null,
      poolName: null,
      round: null,
      series: null,
      stageName: null,
      startTimeLocal: "2023-05-13T18:00:00",
      startTimeUTC: "2023-05-13T15:00:00",
      status: "CONFIRMED",
      statusLabel: "Maç Bitti",
      timesUnconfirmed: null,
      timezone: "Asia/Istanbul",
      venue: "Sinan Erdem Spor Salonu",
      venueId: "0447c62c-32c1-11ed-aba0-e5c084993cbf",
      venueLink:
        "&~w=v~eJwly7sNgDAMANFVItdYsp0EbMZALEB-FRXQIXaHiPKkezecMDuoWyotckAvmZC5FkwxGEokyareChsMDvY-XweuS6_Wi4ilBqZOw0-tqX40Nhote50yPC82DBki",
    },
    fixtureDetailText: {
      ended: "Bitti",
      live: "Canlı",
      startingSoon: "Yakında başlıyor",
      timeUntilStart: "Başlamaya kalan süre",
      time_score: "TimeScore",
    },
    gameStageLabels: {
      all: "Tüm",
      final: "Final",
    },
    locale: "tr-TR",
    locales: [
      ["en-EN", "English"],
      ["tr-TR", "Turkish"],
    ],
    periodData: {
      periodLabels: {
        1: "Ç1",
        2: "Ç2",
        3: "Ç3",
        4: "Ç4",
        11: "UZ1",
        12: "UZ2",
        13: "UZ3",
        14: "UZ4",
        15: "UZ5",
        16: "UZ6",
      },
      teamScores: {
        "a82ec9ef-32c2-11ed-93ce-c5cd151fd515": [
          {
            periodId: 1,
            score: 26,
          },
          {
            periodId: 2,
            score: 19,
          },
          {
            periodId: 3,
            score: 34,
          },
          {
            periodId: 4,
            score: 23,
          },
        ],
        "af7e4c88-32c2-11ed-b619-7bbcc08f45bf": [
          {
            periodId: 1,
            score: 19,
          },
          {
            periodId: 2,
            score: 18,
          },
          {
            periodId: 3,
            score: 13,
          },
          {
            periodId: 4,
            score: 37,
          },
        ],
      },
    },
    seasonId: "eabdf514-32c0-11ed-b549-2502c8839d19",
    seasons: {
      competitions: {
        "3589e7e6-41ca-11ee-b57b-1f59b4185778": {
          name: "BGL Ön Eleme Müsabakaları",
        },
      },
      seasons: [
        {
          abbreviationLocal: null,
          competitionId: "3589e7e6-41ca-11ee-b57b-1f59b4185778",
          link: "&~w=f~eJyrVipWslJQMjZNTUqysDDQNTFMTtQ1NExN1U00N7fQtTQ3Mk01MjZOtTBIUtJRUMoBKS4p0g0JUqoFAL5DDuU",
          nameLocal: "2023-2024",
          seasonId: "35ebb880-41ca-11ee-a778-9725e233e80b",
          year: 2023,
        },
      ],
    },
    statistics: {
      away: {
        entity: {
          assists: 17,
          blocks: 2,
          efficiency: 96,
          fieldGoalsAttempted: 65,
          fieldGoalsMade: 30,
          fieldGoalsPercentage: 46.15385,
          foulsDrawn: 17,
          foulsTotal: 20,
          freeThrowsAttempted: 20,
          freeThrowsMade: 18,
          freeThrowsPercentage: 90,
          minutes: "PT200M",
          plusMinus: null,
          points: 87,
          pointsThreeAttempted: 27,
          pointsThreeMade: 9,
          pointsThreePercentage: 33.33333,
          pointsTwoAttempted: 38,
          pointsTwoMade: 21,
          pointsTwoPercentage: 55.26316,
          rebounds: 37,
          reboundsDefensive: 22,
          reboundsOffensive: 15,
          steals: 8,
          turnovers: 18,
        },
        extra: {
          rebounds: 3,
          reboundsDefensive: 1,
          reboundsOffensive: 2,
          turnovers: 0,
        },
        persons: [
          {
            active: false,
            bib: "9",
            didNotPlayReason: null,
            entityId: "af7e4c88-32c2-11ed-b619-7bbcc08f45bf",
            personId: "3eeb3959-3e47-11ed-925a-7f57b10ba274",
            personImage:
              "https://images.dc.prod.cloud.atriumsports.com/b179b/f46ae034a57648fd9d473ce68b372c77",
            personLink: null,
            personName: "SEMİH ERDEN",
            position: null,
            starter: true,
            statistics: {
              assists: 0,
              blocks: 0,
              efficiency: -2,
              fieldGoalsAttempted: 2,
              fieldGoalsMade: 0,
              fieldGoalsPercentage: 0,
              foulsDrawn: 0,
              foulsTotal: 2,
              freeThrowsAttempted: 0,
              freeThrowsMade: 0,
              freeThrowsPercentage: null,
              minutes: "PT13M15S",
              plusMinus: 1,
              points: 0,
              pointsThreeAttempted: 0,
              pointsThreeMade: 0,
              pointsThreePercentage: null,
              pointsTwoAttempted: 2,
              pointsTwoMade: 0,
              pointsTwoPercentage: 0,
              rebounds: 2,
              reboundsDefensive: 1,
              reboundsOffensive: 1,
              steals: 0,
              turnovers: 2,
            },
          },
          {
            active: false,
            bib: "83",
            didNotPlayReason: null,
            entityId: "af7e4c88-32c2-11ed-b619-7bbcc08f45bf",
            personId: "659fc8e7-3e65-11ed-aed6-87d321422d62",
            personImage:
              "https://images.dc.prod.cloud.atriumsports.com/b179b/c518402249c740538f331a3b70761eb7",
            personLink: null,
            personName: "AXEL BOUTEILLE",
            position: null,
            starter: true,
            statistics: {
              assists: 2,
              blocks: 0,
              efficiency: 12,
              fieldGoalsAttempted: 10,
              fieldGoalsMade: 5,
              fieldGoalsPercentage: 50,
              foulsDrawn: 0,
              foulsTotal: 0,
              freeThrowsAttempted: 0,
              freeThrowsMade: 0,
              freeThrowsPercentage: null,
              minutes: "PT23M15S",
              plusMinus: -12,
              points: 11,
              pointsThreeAttempted: 3,
              pointsThreeMade: 1,
              pointsThreePercentage: 33.33333,
              pointsTwoAttempted: 7,
              pointsTwoMade: 4,
              pointsTwoPercentage: 57.14286,
              rebounds: 6,
              reboundsDefensive: 4,
              reboundsOffensive: 2,
              steals: 0,
              turnovers: 2,
            },
          },
          {
            active: false,
            bib: "22",
            didNotPlayReason: null,
            entityId: "af7e4c88-32c2-11ed-b619-7bbcc08f45bf",
            personId: "664baa89-3e65-11ed-a8e5-252443b67d67",
            personImage:
              "https://images.dc.prod.cloud.atriumsports.com/b179b/0351987794154168aa7135375584fec1",
            personLink: null,
            personName: "HOLDYN JERIAN GRANT",
            position: null,
            starter: true,
            statistics: {
              assists: 4,
              blocks: 0,
              efficiency: 14,
              fieldGoalsAttempted: 13,
              fieldGoalsMade: 5,
              fieldGoalsPercentage: 38.46154,
              foulsDrawn: 5,
              foulsTotal: 4,
              freeThrowsAttempted: 3,
              freeThrowsMade: 3,
              freeThrowsPercentage: 100,
              minutes: "PT36M30S",
              plusMinus: -10,
              points: 15,
              pointsThreeAttempted: 6,
              pointsThreeMade: 2,
              pointsThreePercentage: 33.33333,
              pointsTwoAttempted: 7,
              pointsTwoMade: 3,
              pointsTwoPercentage: 42.85714,
              rebounds: 2,
              reboundsDefensive: 1,
              reboundsOffensive: 1,
              steals: 2,
              turnovers: 1,
            },
          },
          {
            active: false,
            bib: "77",
            didNotPlayReason: null,
            entityId: "af7e4c88-32c2-11ed-b619-7bbcc08f45bf",
            personId: "679d2a69-3e65-11ed-b5ca-252443b67d67",
            personImage:
              "https://images.dc.prod.cloud.atriumsports.com/b179b/c61d334406e6454a97b43be416339b64",
            personLink: null,
            personName: "NATHAN MICHAEL SESTINA",
            position: null,
            starter: false,
            statistics: {
              assists: 0,
              blocks: 1,
              efficiency: 13,
              fieldGoalsAttempted: 7,
              fieldGoalsMade: 4,
              fieldGoalsPercentage: 57.14286,
              foulsDrawn: 2,
              foulsTotal: 4,
              freeThrowsAttempted: 4,
              freeThrowsMade: 3,
              freeThrowsPercentage: 75,
              minutes: "PT19M47S",
              plusMinus: -9,
              points: 14,
              pointsThreeAttempted: 6,
              pointsThreeMade: 3,
              pointsThreePercentage: 50,
              pointsTwoAttempted: 1,
              pointsTwoMade: 1,
              pointsTwoPercentage: 100,
              rebounds: 3,
              reboundsDefensive: 2,
              reboundsOffensive: 1,
              steals: 1,
              turnovers: 2,
            },
          },
          {
            active: false,
            bib: "5",
            didNotPlayReason: null,
            entityId: "af7e4c88-32c2-11ed-b619-7bbcc08f45bf",
            personId: "8a1ab93e-37f5-11ed-8438-dbe1e2826edb",
            personImage:
              "https://images.dc.prod.cloud.atriumsports.com/b179b/f8d32865521c4e40a4a984851dd314ed",
            personLink: null,
            personName: "EMİRCAN KOŞUT",
            position: null,
            starter: false,
            statistics: {
              assists: null,
              blocks: null,
              efficiency: 0,
              fieldGoalsAttempted: null,
              fieldGoalsMade: null,
              fieldGoalsPercentage: null,
              foulsDrawn: null,
              foulsTotal: 0,
              freeThrowsAttempted: null,
              freeThrowsMade: 0,
              freeThrowsPercentage: null,
              minutes: null,
              plusMinus: null,
              points: 0,
              pointsThreeAttempted: null,
              pointsThreeMade: null,
              pointsThreePercentage: null,
              pointsTwoAttempted: null,
              pointsTwoMade: null,
              pointsTwoPercentage: null,
              rebounds: null,
              reboundsDefensive: null,
              reboundsOffensive: null,
              steals: null,
              turnovers: null,
            },
          },
          {
            active: false,
            bib: "11",
            didNotPlayReason: null,
            entityId: "af7e4c88-32c2-11ed-b619-7bbcc08f45bf",
            personId: "ca8fdadc-34fa-11ed-9a6b-cbc8545df8c6",
            personImage:
              "https://images.dc.prod.cloud.atriumsports.com/b179b/26f968ac0db64533a8abd3f87d5c8a11",
            personLink: null,
            personName: "BERK DEMİR",
            position: null,
            starter: true,
            statistics: {
              assists: 1,
              blocks: 0,
              efficiency: 2,
              fieldGoalsAttempted: 0,
              fieldGoalsMade: 0,
              fieldGoalsPercentage: null,
              foulsDrawn: 0,
              foulsTotal: 2,
              freeThrowsAttempted: 0,
              freeThrowsMade: 0,
              freeThrowsPercentage: null,
              minutes: "PT16M35S",
              plusMinus: 4,
              points: 0,
              pointsThreeAttempted: 0,
              pointsThreeMade: 0,
              pointsThreePercentage: null,
              pointsTwoAttempted: 0,
              pointsTwoMade: 0,
              pointsTwoPercentage: null,
              rebounds: 3,
              reboundsDefensive: 2,
              reboundsOffensive: 1,
              steals: 0,
              turnovers: 2,
            },
          },
          {
            active: false,
            bib: "33",
            didNotPlayReason: null,
            entityId: "af7e4c88-32c2-11ed-b619-7bbcc08f45bf",
            personId: "ccb9c275-34fa-11ed-a31c-9bf1878ace6e",
            personImage:
              "https://images.dc.prod.cloud.atriumsports.com/b179b/7d8815cf373e4e2eb3842056d7534acd",
            personLink: null,
            personName: "ERKAN YILMAZ",
            position: null,
            starter: false,
            statistics: {
              assists: 2,
              blocks: 1,
              efficiency: 11,
              fieldGoalsAttempted: 5,
              fieldGoalsMade: 3,
              fieldGoalsPercentage: 60,
              foulsDrawn: 0,
              foulsTotal: 2,
              freeThrowsAttempted: 0,
              freeThrowsMade: 0,
              freeThrowsPercentage: null,
              minutes: "PT20M29S",
              plusMinus: -25,
              points: 6,
              pointsThreeAttempted: 2,
              pointsThreeMade: 0,
              pointsThreePercentage: 0,
              pointsTwoAttempted: 3,
              pointsTwoMade: 3,
              pointsTwoPercentage: 100,
              rebounds: 2,
              reboundsDefensive: 1,
              reboundsOffensive: 1,
              steals: 3,
              turnovers: 1,
            },
          },
          {
            active: false,
            bib: "7",
            didNotPlayReason: null,
            entityId: "af7e4c88-32c2-11ed-b619-7bbcc08f45bf",
            personId: "cd862f6e-34fa-11ed-97c5-9b4a6ede45f7",
            personImage:
              "https://images.dc.prod.cloud.atriumsports.com/b179b/618677d9669e4591834dcf2f7c2af8dc",
            personLink: null,
            personName: "RIDVAN ÖNCEL",
            position: null,
            starter: true,
            statistics: {
              assists: 1,
              blocks: 0,
              efficiency: 6,
              fieldGoalsAttempted: 5,
              fieldGoalsMade: 3,
              fieldGoalsPercentage: 60,
              foulsDrawn: 0,
              foulsTotal: 0,
              freeThrowsAttempted: 0,
              freeThrowsMade: 0,
              freeThrowsPercentage: null,
              minutes: "PT13M53S",
              plusMinus: -9,
              points: 7,
              pointsThreeAttempted: 2,
              pointsThreeMade: 1,
              pointsThreePercentage: 50,
              pointsTwoAttempted: 3,
              pointsTwoMade: 2,
              pointsTwoPercentage: 66.66667,
              rebounds: 1,
              reboundsDefensive: 1,
              reboundsOffensive: 0,
              steals: 2,
              turnovers: 3,
            },
          },
          {
            active: false,
            bib: "2",
            didNotPlayReason: null,
            entityId: "af7e4c88-32c2-11ed-b619-7bbcc08f45bf",
            personId: "ce09a79c-34fa-11ed-924b-cbc8545df8c6",
            personImage:
              "https://images.dc.prod.cloud.atriumsports.com/b179b/f8e2411afc254e4cb6a0333fe7e37afe",
            personLink: null,
            personName: "BORAN GÜLER",
            position: null,
            starter: false,
            statistics: {
              assists: 1,
              blocks: 0,
              efficiency: 4,
              fieldGoalsAttempted: 2,
              fieldGoalsMade: 1,
              fieldGoalsPercentage: 50,
              foulsDrawn: 2,
              foulsTotal: 0,
              freeThrowsAttempted: 3,
              freeThrowsMade: 2,
              freeThrowsPercentage: 66.66667,
              minutes: "PT8M42S",
              plusMinus: 16,
              points: 4,
              pointsThreeAttempted: 1,
              pointsThreeMade: 0,
              pointsThreePercentage: 0,
              pointsTwoAttempted: 1,
              pointsTwoMade: 1,
              pointsTwoPercentage: 100,
              rebounds: 1,
              reboundsDefensive: 1,
              reboundsOffensive: 0,
              steals: 0,
              turnovers: 0,
            },
          },
          {
            active: false,
            bib: "50",
            didNotPlayReason: null,
            entityId: "af7e4c88-32c2-11ed-b619-7bbcc08f45bf",
            personId: "df6c9661-96ab-11ed-b2b4-c370254c177f",
            personImage: null,
            personLink: null,
            personName: "MICHAEL ERIC",
            position: null,
            starter: false,
            statistics: {
              assists: 0,
              blocks: 0,
              efficiency: 18,
              fieldGoalsAttempted: 12,
              fieldGoalsMade: 6,
              fieldGoalsPercentage: 50,
              foulsDrawn: 4,
              foulsTotal: 4,
              freeThrowsAttempted: 3,
              freeThrowsMade: 3,
              freeThrowsPercentage: 100,
              minutes: "PT17M",
              plusMinus: -9,
              points: 15,
              pointsThreeAttempted: 0,
              pointsThreeMade: 0,
              pointsThreePercentage: null,
              pointsTwoAttempted: 12,
              pointsTwoMade: 6,
              pointsTwoPercentage: 50,
              rebounds: 11,
              reboundsDefensive: 6,
              reboundsOffensive: 5,
              steals: 0,
              turnovers: 2,
            },
          },
          {
            active: false,
            bib: "4",
            didNotPlayReason: null,
            entityId: "af7e4c88-32c2-11ed-b619-7bbcc08f45bf",
            personId: "dfda1d61-3b54-11ed-a9a1-9f0c226e15b6",
            personImage:
              "https://images.dc.prod.cloud.atriumsports.com/b179b/95106b78462447bdafe50f6b7a67ff24",
            personLink: null,
            personName: "MEHMET YAĞMUR",
            position: null,
            starter: false,
            statistics: {
              assists: 0,
              blocks: 0,
              efficiency: -1,
              fieldGoalsAttempted: 1,
              fieldGoalsMade: 0,
              fieldGoalsPercentage: 0,
              foulsDrawn: 0,
              foulsTotal: 0,
              freeThrowsAttempted: 0,
              freeThrowsMade: 0,
              freeThrowsPercentage: null,
              minutes: "PT1M28S",
              plusMinus: -3,
              points: 0,
              pointsThreeAttempted: 1,
              pointsThreeMade: 0,
              pointsThreePercentage: 0,
              pointsTwoAttempted: 0,
              pointsTwoMade: 0,
              pointsTwoPercentage: null,
              rebounds: 1,
              reboundsDefensive: 0,
              reboundsOffensive: 1,
              steals: 0,
              turnovers: 1,
            },
          },
          {
            active: false,
            bib: "21",
            didNotPlayReason: null,
            entityId: "af7e4c88-32c2-11ed-b619-7bbcc08f45bf",
            personId: "e41d2f11-3a61-11ed-909a-8d05ddec8c16",
            personImage:
              "https://images.dc.prod.cloud.atriumsports.com/b179b/5b644828c97946e3940e7e46b37b69fe",
            personLink: null,
            personName: "TONY CHRISTOPHER TAYLOR",
            position: null,
            starter: false,
            statistics: {
              assists: 6,
              blocks: 0,
              efficiency: 16,
              fieldGoalsAttempted: 8,
              fieldGoalsMade: 3,
              fieldGoalsPercentage: 37.5,
              foulsDrawn: 4,
              foulsTotal: 2,
              freeThrowsAttempted: 7,
              freeThrowsMade: 7,
              freeThrowsPercentage: 100,
              minutes: "PT29M6S",
              plusMinus: -19,
              points: 15,
              pointsThreeAttempted: 6,
              pointsThreeMade: 2,
              pointsThreePercentage: 33.33333,
              pointsTwoAttempted: 2,
              pointsTwoMade: 1,
              pointsTwoPercentage: 50,
              rebounds: 2,
              reboundsDefensive: 2,
              reboundsOffensive: 0,
              steals: 0,
              turnovers: 2,
            },
          },
        ],
        totalEntityStats: {
          biggestLead: 4,
          biggestScoringRun: 9,
          leadChanges: 10,
          pointsFastBreak: 12,
          pointsFromBench: 54,
          pointsFromTurnover: 9,
          pointsInThePaint: 32,
          pointsSecondChance: 12,
          timeInLead: "PT4M58S",
        },
      },
      boxScoreLabels: {
        entity: "Team/Koç",
        sorting: {
          active: "Sahada",
          bib: "Number",
          sortBy: "Sort by",
          starter: "Starter",
        },
        total: "Total",
      },
      entitiesLabels: [
        {
          code: "En Büyük Fark",
          key: "biggestLead",
          name: "EBF",
        },
        {
          code: "Liderlik Değişimi",
          key: "leadChanges",
          name: "LD",
        },
        {
          code: "Top Kaybından sonra Sayı",
          key: "pointsFromTurnover",
          name: "HGS",
        },
        {
          code: "Benchten Gelen Sayı",
          key: "pointsFromBench",
          name: "BGS",
        },
        {
          code: "İkinci Şans Sayısı",
          key: "pointsSecondChance",
          name: "İŞS",
        },
        {
          code: "Fast Break Sayı",
          key: "pointsFastBreak",
          name: "FBS",
        },
        {
          code: "Boyalı Alan Sayısı",
          key: "pointsInThePaint",
          name: "BAS",
        },
        {
          code: "Liderlik Süresi",
          key: "timeInLead",
          name: "LS",
        },
        {
          code: "En Büyük Seri",
          key: "biggestScoringRun",
          name: "EBS",
        },
      ],
      headers: [
        {
          key: "bib",
          name: "#",
        },
        {
          key: "name",
          name: "Name",
        },
        {
          code: "Dakika",
          key: "minutes",
          name: "DK",
        },
        {
          code: "Başarılı Atış Girişimi",
          key: "fieldGoalsMade",
          name: "BAG",
        },
        {
          code: "Atış Girişimi",
          key: "fieldGoalsAttempted",
          name: "AG",
        },
        {
          code: "Atış Girişimi Yüzdesi",
          key: "fieldGoalsPercentage",
          name: "AGY",
        },
        {
          code: "İki Sayı Başarılı",
          key: "pointsTwoMade",
          name: "2SB",
        },
        {
          code: "İki Sayı Deneme",
          key: "pointsTwoAttempted",
          name: "2SD",
        },
        {
          code: "İki Sayı Yüzdesi",
          key: "pointsTwoPercentage",
          name: "2S%",
        },
        {
          code: "Üç Sayı Başarılı",
          key: "pointsThreeMade",
          name: "3SB",
        },
        {
          code: "Üç Sayılık Deneme",
          key: "pointsThreeAttempted",
          name: "3SD",
        },
        {
          code: "Üç Sayı Yüzdesi",
          key: "pointsThreePercentage",
          name: "3S%",
        },
        {
          code: "Başarılı Serbest Atış",
          key: "freeThrowsMade",
          name: "BSA",
        },
        {
          code: "Serbest Atış Denemesi",
          key: "freeThrowsAttempted",
          name: "SA",
        },
        {
          code: "Serbest Atış Yüzdesi",
          key: "freeThrowsPercentage",
          name: "SA%",
        },
        {
          code: "Hücum Ribaundu",
          key: "reboundsOffensive",
          name: "HR",
        },
        {
          code: "Savunma Ribaundu",
          key: "reboundsDefensive",
          name: "SR",
        },
        {
          code: "Ribaund",
          key: "rebounds",
          name: "RİB",
        },
        {
          code: "Asist",
          key: "assists",
          name: "AS",
        },
        {
          code: "Top Kaybı",
          key: "turnovers",
          name: "TK",
        },
        {
          code: "Top Çalma",
          key: "steals",
          name: "TÇ",
        },
        {
          code: "Blok",
          key: "blocks",
          name: "BL",
        },
        {
          code: "Faul",
          key: "foulsTotal",
          name: "FA",
        },
        {
          code: "Yapılan Faul",
          key: "foulsDrawn",
          name: "YF",
        },
        {
          code: "Artı Eksi",
          key: "plusMinus",
          name: "+/-",
        },
        {
          code: "Verimlilik Puanı",
          key: "efficiency",
          name: "VP",
        },
        {
          code: "Sayı",
          key: "points",
          name: "SY",
        },
      ],
      home: {
        entity: {
          assists: 25,
          blocks: 2,
          efficiency: 127,
          fieldGoalsAttempted: 60,
          fieldGoalsMade: 33,
          fieldGoalsPercentage: 55,
          foulsDrawn: 20,
          foulsTotal: 17,
          freeThrowsAttempted: 27,
          freeThrowsMade: 24,
          freeThrowsPercentage: 88.88889,
          minutes: "PT200M",
          plusMinus: null,
          points: 102,
          pointsThreeAttempted: 28,
          pointsThreeMade: 12,
          pointsThreePercentage: 42.85714,
          pointsTwoAttempted: 32,
          pointsTwoMade: 21,
          pointsTwoPercentage: 65.625,
          rebounds: 26,
          reboundsDefensive: 21,
          reboundsOffensive: 5,
          steals: 12,
          turnovers: 10,
        },
        extra: {
          rebounds: 2,
          reboundsDefensive: 1,
          reboundsOffensive: 1,
          turnovers: 2,
        },
        persons: [
          {
            active: false,
            bib: "14",
            didNotPlayReason: null,
            entityId: "a82ec9ef-32c2-11ed-93ce-c5cd151fd515",
            personId: "0fa420c0-32c3-11ed-8146-8b44c5fdc3f8",
            personImage:
              "https://images.dc.prod.cloud.atriumsports.com/b179b/acc3341e386042929c736ae16944517e",
            personLink: null,
            personName: "FURKAN HALTALI",
            position: null,
            starter: false,
            statistics: {
              assists: 0,
              blocks: 0,
              efficiency: 2,
              fieldGoalsAttempted: 0,
              fieldGoalsMade: 0,
              fieldGoalsPercentage: null,
              foulsDrawn: 0,
              foulsTotal: 4,
              freeThrowsAttempted: 0,
              freeThrowsMade: 0,
              freeThrowsPercentage: null,
              minutes: "PT9M5S",
              plusMinus: -5,
              points: 0,
              pointsThreeAttempted: 0,
              pointsThreeMade: 0,
              pointsThreePercentage: null,
              pointsTwoAttempted: 0,
              pointsTwoMade: 0,
              pointsTwoPercentage: null,
              rebounds: 2,
              reboundsDefensive: 1,
              reboundsOffensive: 1,
              steals: 1,
              turnovers: 1,
            },
          },
          {
            active: false,
            bib: "0",
            didNotPlayReason: null,
            entityId: "a82ec9ef-32c2-11ed-93ce-c5cd151fd515",
            personId: "450e1ca2-40c4-11ed-9de9-11048ec7d273",
            personImage:
              "https://images.dc.prod.cloud.atriumsports.com/b179b/dffe1b13b6cc4f0fb6be9529045c07e8",
            personLink: null,
            personName: "DESHANE DAVİS LARKİN",
            position: null,
            starter: true,
            statistics: {
              assists: 2,
              blocks: 0,
              efficiency: 11,
              fieldGoalsAttempted: 7,
              fieldGoalsMade: 3,
              fieldGoalsPercentage: 42.85714,
              foulsDrawn: 3,
              foulsTotal: 2,
              freeThrowsAttempted: 4,
              freeThrowsMade: 3,
              freeThrowsPercentage: 75,
              minutes: "PT27M28S",
              plusMinus: 9,
              points: 11,
              pointsThreeAttempted: 5,
              pointsThreeMade: 2,
              pointsThreePercentage: 40,
              pointsTwoAttempted: 2,
              pointsTwoMade: 1,
              pointsTwoPercentage: 50,
              rebounds: 4,
              reboundsDefensive: 4,
              reboundsOffensive: 0,
              steals: 1,
              turnovers: 2,
            },
          },
          {
            active: false,
            bib: "17",
            didNotPlayReason: null,
            entityId: "a82ec9ef-32c2-11ed-93ce-c5cd151fd515",
            personId: "80713b63-3652-11ed-b43a-dd6fa35f94e3",
            personImage:
              "https://images.dc.prod.cloud.atriumsports.com/b179b/ce944392d1a14f64b431bd3a6c3592fb",
            personLink: null,
            personName: "MEHMET EFE DEMİREL",
            position: null,
            starter: false,
            statistics: {
              assists: 0,
              blocks: 0,
              efficiency: -1,
              fieldGoalsAttempted: 1,
              fieldGoalsMade: 0,
              fieldGoalsPercentage: 0,
              foulsDrawn: 0,
              foulsTotal: 1,
              freeThrowsAttempted: 0,
              freeThrowsMade: 0,
              freeThrowsPercentage: null,
              minutes: "PT5M25S",
              plusMinus: 2,
              points: 0,
              pointsThreeAttempted: 1,
              pointsThreeMade: 0,
              pointsThreePercentage: 0,
              pointsTwoAttempted: 0,
              pointsTwoMade: 0,
              pointsTwoPercentage: null,
              rebounds: 0,
              reboundsDefensive: 0,
              reboundsOffensive: 0,
              steals: 0,
              turnovers: 0,
            },
          },
          {
            active: false,
            bib: "22",
            didNotPlayReason: null,
            entityId: "a82ec9ef-32c2-11ed-93ce-c5cd151fd515",
            personId: "a7d029be-3a48-11ed-a24c-5deb87c31614",
            personImage:
              "https://images.dc.prod.cloud.atriumsports.com/b179b/df9167e68ff34c58b058dc14865b67ec",
            personLink: null,
            personName: "VASILIJE MICIC",
            position: null,
            starter: false,
            statistics: {
              assists: 4,
              blocks: 0,
              efficiency: 24,
              fieldGoalsAttempted: 10,
              fieldGoalsMade: 8,
              fieldGoalsPercentage: 80,
              foulsDrawn: 3,
              foulsTotal: 2,
              freeThrowsAttempted: 2,
              freeThrowsMade: 2,
              freeThrowsPercentage: 100,
              minutes: "PT28M21S",
              plusMinus: 12,
              points: 20,
              pointsThreeAttempted: 3,
              pointsThreeMade: 2,
              pointsThreePercentage: 66.66667,
              pointsTwoAttempted: 7,
              pointsTwoMade: 6,
              pointsTwoPercentage: 85.71429,
              rebounds: 2,
              reboundsDefensive: 2,
              reboundsOffensive: 0,
              steals: 1,
              turnovers: 1,
            },
          },
          {
            active: false,
            bib: "19",
            didNotPlayReason: null,
            entityId: "a82ec9ef-32c2-11ed-93ce-c5cd151fd515",
            personId: "f24e6212-3a7a-11ed-b326-3d2c0d3fea11",
            personImage:
              "https://images.dc.prod.cloud.atriumsports.com/b179b/8f043e315dba4b8dad93ff7e7e1a8eb2",
            personLink: null,
            personName: "AHMET BUĞRAHAN TUNCER",
            position: null,
            starter: false,
            statistics: {
              assists: 2,
              blocks: 0,
              efficiency: 1,
              fieldGoalsAttempted: 5,
              fieldGoalsMade: 1,
              fieldGoalsPercentage: 20,
              foulsDrawn: 0,
              foulsTotal: 1,
              freeThrowsAttempted: 0,
              freeThrowsMade: 0,
              freeThrowsPercentage: null,
              minutes: "PT14M31S",
              plusMinus: 1,
              points: 3,
              pointsThreeAttempted: 3,
              pointsThreeMade: 1,
              pointsThreePercentage: 33.33333,
              pointsTwoAttempted: 2,
              pointsTwoMade: 0,
              pointsTwoPercentage: 0,
              rebounds: 2,
              reboundsDefensive: 2,
              reboundsOffensive: 0,
              steals: 0,
              turnovers: 2,
            },
          },
          {
            active: false,
            bib: "1",
            didNotPlayReason: null,
            entityId: "a82ec9ef-32c2-11ed-93ce-c5cd151fd515",
            personId: "fc39af9c-32c2-11ed-9b3a-dd2eb64e2196",
            personImage:
              "https://images.dc.prod.cloud.atriumsports.com/b179b/7bc370702cee45d995aa32def6eec2d6",
            personLink: null,
            personName: "RODRIGUE BEAUBOIS",
            position: null,
            starter: true,
            statistics: {
              assists: 4,
              blocks: 1,
              efficiency: 18,
              fieldGoalsAttempted: 8,
              fieldGoalsMade: 5,
              fieldGoalsPercentage: 62.5,
              foulsDrawn: 0,
              foulsTotal: 1,
              freeThrowsAttempted: 1,
              freeThrowsMade: 1,
              freeThrowsPercentage: 100,
              minutes: "PT26M14S",
              plusMinus: 16,
              points: 15,
              pointsThreeAttempted: 6,
              pointsThreeMade: 4,
              pointsThreePercentage: 66.66667,
              pointsTwoAttempted: 2,
              pointsTwoMade: 1,
              pointsTwoPercentage: 50,
              rebounds: 2,
              reboundsDefensive: 2,
              reboundsOffensive: 0,
              steals: 0,
              turnovers: 1,
            },
          },
          {
            active: false,
            bib: "5",
            didNotPlayReason: null,
            entityId: "a82ec9ef-32c2-11ed-93ce-c5cd151fd515",
            personId: "fceb0a4b-32c2-11ed-a0ef-dd2eb64e2196",
            personImage:
              "https://images.dc.prod.cloud.atriumsports.com/b179b/e6d06fd086604f9380a736cb1e202f7c",
            personLink: null,
            personName: "KARAHAN TUAN EFEOĞLU",
            position: null,
            starter: false,
            statistics: {
              assists: null,
              blocks: null,
              efficiency: 0,
              fieldGoalsAttempted: null,
              fieldGoalsMade: null,
              fieldGoalsPercentage: null,
              foulsDrawn: null,
              foulsTotal: 0,
              freeThrowsAttempted: null,
              freeThrowsMade: 0,
              freeThrowsPercentage: null,
              minutes: null,
              plusMinus: null,
              points: 0,
              pointsThreeAttempted: null,
              pointsThreeMade: null,
              pointsThreePercentage: null,
              pointsTwoAttempted: null,
              pointsTwoMade: null,
              pointsTwoPercentage: null,
              rebounds: null,
              reboundsDefensive: null,
              reboundsOffensive: null,
              steals: null,
              turnovers: null,
            },
          },
          {
            active: false,
            bib: "6",
            didNotPlayReason: null,
            entityId: "a82ec9ef-32c2-11ed-93ce-c5cd151fd515",
            personId: "fd719cb3-32c2-11ed-bc82-8b44c5fdc3f8",
            personImage:
              "https://images.dc.prod.cloud.atriumsports.com/b179b/56c255978d4f407984972d4e8bc0709d",
            personLink: null,
            personName: "ELIJAH BRIGHAM BRYANT",
            position: null,
            starter: true,
            statistics: {
              assists: 6,
              blocks: 0,
              efficiency: 20,
              fieldGoalsAttempted: 9,
              fieldGoalsMade: 4,
              fieldGoalsPercentage: 44.44444,
              foulsDrawn: 3,
              foulsTotal: 1,
              freeThrowsAttempted: 4,
              freeThrowsMade: 4,
              freeThrowsPercentage: 100,
              minutes: "PT33M58S",
              plusMinus: 9,
              points: 13,
              pointsThreeAttempted: 4,
              pointsThreeMade: 1,
              pointsThreePercentage: 25,
              pointsTwoAttempted: 5,
              pointsTwoMade: 3,
              pointsTwoPercentage: 60,
              rebounds: 4,
              reboundsDefensive: 4,
              reboundsOffensive: 0,
              steals: 2,
              turnovers: 0,
            },
          },
          {
            active: false,
            bib: "12",
            didNotPlayReason: null,
            entityId: "a82ec9ef-32c2-11ed-93ce-c5cd151fd515",
            personId: "fdf9b1ca-32c2-11ed-aa1b-8b44c5fdc3f8",
            personImage:
              "https://images.dc.prod.cloud.atriumsports.com/b179b/f10e631d405e49c6b91c9277cfb2ed8a",
            personLink: null,
            personName: "WILL CLYBURN",
            position: null,
            starter: true,
            statistics: {
              assists: 4,
              blocks: 0,
              efficiency: 23,
              fieldGoalsAttempted: 13,
              fieldGoalsMade: 6,
              fieldGoalsPercentage: 46.15385,
              foulsDrawn: 4,
              foulsTotal: 2,
              freeThrowsAttempted: 4,
              freeThrowsMade: 4,
              freeThrowsPercentage: 100,
              minutes: "PT26M38S",
              plusMinus: 22,
              points: 18,
              pointsThreeAttempted: 6,
              pointsThreeMade: 2,
              pointsThreePercentage: 33.33333,
              pointsTwoAttempted: 7,
              pointsTwoMade: 4,
              pointsTwoPercentage: 57.14286,
              rebounds: 3,
              reboundsDefensive: 1,
              reboundsOffensive: 2,
              steals: 5,
              turnovers: 0,
            },
          },
          {
            active: false,
            bib: "41",
            didNotPlayReason: null,
            entityId: "a82ec9ef-32c2-11ed-93ce-c5cd151fd515",
            personId: "ff119199-32c2-11ed-959a-8b44c5fdc3f8",
            personImage:
              "https://images.dc.prod.cloud.atriumsports.com/b179b/36f3bcbec80b450cb360562915828136",
            personLink: null,
            personName: "ANTE TONI ZIZIC",
            position: null,
            starter: true,
            statistics: {
              assists: 3,
              blocks: 1,
              efficiency: 29,
              fieldGoalsAttempted: 7,
              fieldGoalsMade: 6,
              fieldGoalsPercentage: 85.71429,
              foulsDrawn: 7,
              foulsTotal: 3,
              freeThrowsAttempted: 12,
              freeThrowsMade: 10,
              freeThrowsPercentage: 83.33333,
              minutes: "PT28M20S",
              plusMinus: 9,
              points: 22,
              pointsThreeAttempted: 0,
              pointsThreeMade: 0,
              pointsThreePercentage: null,
              pointsTwoAttempted: 7,
              pointsTwoMade: 6,
              pointsTwoPercentage: 85.71429,
              rebounds: 5,
              reboundsDefensive: 4,
              reboundsOffensive: 1,
              steals: 2,
              turnovers: 1,
            },
          },
        ],
        totalEntityStats: {
          biggestLead: 29,
          biggestScoringRun: 10,
          leadChanges: 10,
          pointsFastBreak: 27,
          pointsFromBench: 23,
          pointsFromTurnover: 24,
          pointsInThePaint: 40,
          pointsSecondChance: 2,
          timeInLead: "PT33M24S",
        },
      },
    },
    sub: "statistics",
    summary: {},
    tabs: [
      {
        active: true,
        label: "Box Score",
        link: "&~w=f~eJwljEkKwzAMAL8SdK5A8pJIfUbJBxLZhkBOtU8p_XsjepxhmA90eE5Qt720zAljMELmWnDPSTFkCiYStbDCY4LT4_HG9eV0OfWxjaOPw7qr5oqIQ01Mfkv_mzaR-5YbzWpRFoPvD4z7HxU",
        sub: "statistics",
      },
      {
        label: "Oyun Akışı",
        link: "&~w=f~eJwljDkKw0AMAL9iVEcg7WpjKc8w-UD2qlwstqsY_90R6WZgmBN2eE3QPrn2xIIxFELmVjEnMQyJQlGNVtngMcHq8bHhe3H7uo08nLszEYcmTL6R_8a66m-TOj2tRJ0LXDd5uRwM",
        sub: "pbp",
      },
      {
        label: "Atış Grafiği",
        link: "&~w=f~eJwljMsKg0AMAH9Fcm4g2Ueb9DOk96LZXTwUBN2T0n-voccZhjlhh-cAdZpLy5wwBiNkrgXnnBRDpmAiUQsr3Ab4eNw3fI1Oh9O-rP1ty7R1V80VEYeamPyW_jdtItctN7qrRXkYfH-HJh75",
        sub: "shot_chart",
      },
      {
        label: "Analiz",
        link: "&~w=f~eJwljMsKg0AMAH9FcjaQ7KMmfob4A-s-oCA9uF7a4r_X0OMMw3yhwzxATVtpkQN6lwmZa8EtBkUXyWURr4UVxgF2i88D18XoY5ReaX_3ZzfRTBCxq4HJXuH_0iZyv2Kjh2YvU4brBznzHi4",
        sub: "analysis",
      },
      {
        label: "Liderler",
        link: "&~w=f~eJwlzDkKw0AMQNGrGNURSLPYUo5hcoFZNNVUtiuH3D0RKR98_htOeC5gpfaROWEMjZDZOtacFEOm0ESidlZ4LDA9vg587a7bNa10O073cBNxsMTkq_Rf6RD5rfKgVVuUrcHnCw4vHao",
        sub: "leaders",
      },
    ],
    teamStaff: {
      "a82ec9ef-32c2-11ed-93ce-c5cd151fd515": [
        {
          entityId: "a82ec9ef-32c2-11ed-93ce-c5cd151fd515",
          name: "RODRIGUE BEAUBOIS",
          organizationId: "b179b",
          personId: "fc39af9c-32c2-11ed-9b3a-dd2eb64e2196",
          role: "CAPTAIN",
          roleId: "6064bbc8-f198-11ed-8998-bf370cd0f7d4",
          roleLabel: "Kaptan",
        },
      ],
    },
  },
];
